# Generated by Django 3.0 on 2020-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='username',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
