# Generated by Django 3.0 on 2020-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='gender',
            field=models.CharField(default='male', max_length=50),
        ),
    ]
