# Generated by Django 3.0.5 on 2020-04-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keyword', models.TextField()),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('state', models.CharField(max_length=50)),
                ('type_id', models.IntegerField()),
                ('poster_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('reaction', models.CharField(max_length=50)),
                ('reactor_id', models.IntegerField()),
                ('reacted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('reply_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('reporter_id', models.IntegerField()),
                ('concern', models.TextField()),
                ('reported_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
            ],
        ),
    ]
