# Generated by Django 3.0 on 2020-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.DateTimeField(default='2020-05-06 14:42:37.295705+00:00'),
        ),
        migrations.AddField(
            model_name='username',
            name='time',
            field=models.DateTimeField(default='2020-05-06 14:42:37.295705+00:00'),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.TextField(),
        ),
    ]
