# Generated by Django 3.0 on 2020-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_auto_20200506_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='password',
            field=models.TextField(default='test'),
        ),
    ]
